- hosts: test
  vars:
    - docroot: /var/www/vhosts/{{ ansible_hostname }}
  tasks:
    - name: Install httpd webserver
      yum: pkg=httpd state=installed
      register: installed_httpd
      notify:
        - Start httpd

    - name: Create DocumentRoot folder
      when: installed_httpd|success
      file: state=directory recurse=yes path={{ docroot }}/htdocs owner=apache group=apache
      notify:
        - Reload httpd

  handlers:
    - name: Start httpd
      service: name=httpd state=started

    - name: Reload httpd
      service: name=httpd state=reloaded
