- hosts: test

  tasks:
    # Add the epel-repository.
    - name: Add epel-repository
      yum: name=epel-release state=present
    # Install the repository configuration package.
    #- command: /bin/rpm -ivh http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm
    # Install the web-server.
    - name: Install httpd packages
      yum: name={{ item }} state=present
      with_items:
        - httpd
        - httpd-devel
        - apr
        - apr-util
        - mod_ssl
        - php
    # Start the web-server.
    - name: Start httpd
      service: name=httpd state=started enabled=true
    # Install the database.
    - name: Install mysql packages
      yum: name={{ item }} state=present
      with_items:
        - mysql-server
        - mysql
        - mysql-devel
        - MySQL-python
    # Start the database.
    - name: Start mysqld
      service: name=mysqld state=started enabled=true
    # Create the database and user.
    - mysql_db: name=zabbix state=present
    #- mysql_user: name=root password=12345 priv=*.*:ALL,GRANT state=present
    - mysql_user: name=zabbix password=12345 priv=zabbix.*:ALL,GRANT state=present
    # Install the zabbix-server
    - name: Install zabbix-server packages
      yum: name={{ item }} state=present
      with_items:
        - zabbix-server
        - zabbix-server-mysql
        - zabbix-web
    # Install the dependencies
    - name: Install zabbix-server dependencies
      yum: name={{ item }} state=present
      with_items:
        - make
        - gcc
        - curl-devel
        - net-snmp-devel
        - OpenIPMI-devel
        - libssh2
        - libssh2-devel
        - libxml2
        - libxml2-devel
        - wget
        - net-snmp
        - snmptt
        - net-snmp-utils
    # Copy the zabbix-server configuration.
    - name: Configure zabbix-server
      template: src=zabbix_server.conf.j2 dest=/etc/zabbix/zabbix_server.conf owner=root group=zabbix mode=0640
    # Start the zabbix-server.
    - name: Start zabbix-server
      service: name=zabbix-server state=started
    # Restart the web-server.
    - name: Restart httpd
      service: name=httpd state=restarted
    - mysql_user: name=root password=12345 priv=*.*:ALL,GRANT state=present
